include("packages.jl")
include("TradeOffs_CommonCode.jl")

#BevertonHoltConstant
#Figure 1
let 
    datap040=[BevHoltI_equi(BevHoltPar(τ=τval,p=0.4)) for τval in 0:1:7]
    datap050=[BevHoltI_equi(BevHoltPar(τ=τval,p=0.5)) for τval in 0:1:7]
    datap055=[BevHoltI_equi(BevHoltPar(τ=τval,p=0.55)) for τval in 0:1:7]
    using Random
    equifig = scatter(collect(0:1:7) .+ randn(8) .*0.05, datap040, label="\${\\overline{p}}=0.4\$",markersize=6, color="#440154FF")
    plot!(collect(0:1:7), datap040, label="",linestyle=:dash, color="#440154FF")
    scatter!(collect(0:1:7) .+ randn(8) .*0.05, datap050, label="\${\\overline{p}}=0.5\$",markersize=6, color="#238A8DFF")
    plot!(collect(0:1:7), datap050, label="",linestyle=:dash, color="#238A8DFF")
    scatter!(collect(0:1:7) .+ randn(8) .*0.05, datap055, label="\${\\overline{p}}=0.55\$",markersize=6, color="#FDE725FF")
    plot!(collect(0:1:7), datap055, label="",linestyle=:dash, color="#FDE725FF")
    xlabel!("\$\\tau\$")
    ylabel!("N*(\$\\tau\$)")
    savefig(joinpath(abpath(), "figs/BevHoltI_equi.pdf"))
end

#RickerConstant
#Calculate max and min for Neimark-Sacker
function maxminNS(τval, arange, time, trans)
    maxdata=zeros(length(arange))
    mindata=zeros(length(arange))
    @threads for ai in eachindex(arange)
        timeseries = model_recursion(0.1, time, RickerPar(τ=τval, a=arange[ai], p=0.6, α=0.1, β=0.3, b=200, K=1.0), RickerConstant_model)[trans:end]
        maxdata[ai] = maximum(timeseries)
        mindata[ai] = minimum(timeseries)
    end
    return arange, maxdata, mindata
end

let #create max min N-S data for even tau Ricker constant
    ahigh2=ahigherconstraint(RickerPar(p=0.6, τ=2.0, α=0.1, β=0.3, b=200, K=1.0))
    maxmin2=maxminNS(2.0, 14.385:0.001:ahigh2-0.01, 1000000, 999000)
    ahigh4=ahigherconstraint(RickerPar(p=0.6, τ=4.0, α=0.1, β=0.3, b=200, K=1.0))
    maxmin4=maxminNS(4.0, 12.98:0.005:ahigh4-0.01, 1000000, 999000)
    ahigh6=ahigherconstraint(RickerPar(p=0.6, τ=6.0, α=0.1, β=0.3, b=200, K=1.0))
    maxmin6=maxminNS(6.0, 32.03:0.01:ahigh6-0.01, 1000000, 999000)

    df_maxmin2 = DataFrame(a = maxmin2[1], maximum = maxmin2[2], minimum = maxmin2[3])
    CSV.write("data/maxmin2.csv", df_maxmin2)

    df_maxmin4 = DataFrame(a = maxmin4[1], maximum = maxmin4[2], minimum = maxmin4[3])
    CSV.write("data/maxmin4.csv", df_maxmin4)

    df_maxmin6 = DataFrame(a = maxmin6[1], maximum = maxmin6[2], minimum = maxmin6[3])
    CSV.write("data/maxmin6.csv", df_maxmin6)
end

function findRCvalue(data, aval, stable)
    if stable=="stable"
        return @subset(data, isapprox.(:a, aval; rtol=1e-4)).N1[1]
    elseif stable=="unstable"
        return @subset(data, isapprox.(:a, aval; rtol=1e-4)).N1[1]
    elseif stable=="max"
        return @subset(data, isapprox.(:a, aval; rtol=1e-4)).maximum[1]
    else
        error("Invalid stable type. Use 'stable', 'unstable', or 'max'.")
    end
end

let #Even tau
    datatau2 = cleanxppautdat_onepar("src/xppaut/RickerConstanttau2_a.dat")
    tau2lowerbound = alowerconstraint(RickerPar(p=0.6, τ=2.0, α=0.1, β=0.3, b=200, K=1.0))
    datatau2_filtered = sort(@subset(datatau2, :a .> tau2lowerbound), :a) #.|| :N1 .>= 0
    datatau2s = @subset(datatau2_filtered, :PointTypeName .== "Stable" .&& :N1 .> 0.00)
    datatau2ua = @subset(datatau2_filtered, :PointTypeName .== "Unstable" .&& :N1 .> 6.00)
    datatau2ub = @subset(datatau2_filtered, :PointTypeName .== "Unstable" .&& :N1 .< 1.00)
    datatau4 = cleanxppautdat_onepar("src/xppaut/RickerConstanttau4_a.dat")
    tau4lowerbound = alowerconstraint(RickerPar(p=0.6, τ=4.0, α=0.1, β=0.3, b=200, K=1.0))
    datatau4_filtered = sort(@subset(datatau4, :a .> tau4lowerbound), :a) #.|| :N1 .>= 0
    datatau4s = @subset(datatau4_filtered, :PointTypeName .== "Stable" .&& :N1 .> 0.00)
    datatau4ua = @subset(datatau4_filtered, :PointTypeName .== "Unstable" .&& :N1 .> 6.00)
    datatau4ub = @subset(datatau4_filtered, :PointTypeName .== "Unstable" .&& :N1 .< 1.00)
    datatau6 = cleanxppautdat_onepar("src/xppaut/RickerConstanttau6_a.dat")
    tau6lowerbound = alowerconstraint(RickerPar(p=0.6, τ=6.0, α=0.1, β=0.3, b=200, K=1.0))
    datatau6_filtered = sort(@subset(datatau6, :a .> tau4lowerbound), :a) #.|| :N1 .>= 0
    datatau6s = unique(@subset(datatau6_filtered, :PointTypeName .== "Stable" .&& :N1 .> 0.00), :a)
    datatau6ua = @subset(datatau6_filtered, :PointTypeName .== "Unstable" .&& :N1 .> 6.00)
    datatau6ub = @subset(datatau6_filtered, :PointTypeName .== "Unstable" .&& :N1 .< 1.00)
    ahigh6=ahigherconstraint(RickerPar(p=0.6, τ=6.0, α=0.1, β=0.3, b=200, K=1.0))
    maxmindata2=CSV.read("data/maxmin2.csv", DataFrame)
    maxmindata4=CSV.read("data/maxmin4.csv", DataFrame)
    maxmindata6=CSV.read("data/maxmin6.csv", DataFrame)
    #Time embedding prep
    endtime = 1000000
    finalts = 999000
    timeseries = model_recursion(0.1, endtime, RickerPar(τ=6, p=0.6, a=33.0, α=0.1, β=0.3, K=1.0, b=200), RickerConstant_model)
    df = DataFrame(time = 0:endtime, N = timeseries)
    dfxaxis = @subset(df, :time .>= finalts-6 .&& :time .<= endtime-6)
    dfyaxis = @subset(df, :time .>= finalts)
    dfxaxis.row = 1:nrow(dfxaxis)
    dfyaxis.row = 1:nrow(dfyaxis)
    merged_df = leftjoin(dfxaxis, dfyaxis, on=:row, makeunique=true)
    select!(merged_df, Not([:time, :time_1, :row]))
    timeseriess = model_recursion(0.1, endtime, RickerPar(τ=6, p=0.6, a=32.0, α=0.1, β=0.3, K=1.0, b=200), RickerConstant_model)
    dfs = DataFrame(time = 0:endtime, N = timeseriess)
    dfxaxiss = @subset(dfs, :time .>= finalts-6 .&& :time .<= endtime-6)
    dfyaxiss = @subset(dfs, :time .>= finalts)
    dfxaxiss.row = 1:nrow(dfxaxiss)
    dfyaxiss.row = 1:nrow(dfyaxiss)
    merged_dfs = leftjoin(dfxaxiss, dfyaxiss, on=:row, makeunique=true)
    select!(merged_dfs, Not([:time, :time_1, :row]))

    p1=plot(datatau2s.a, datatau2s.N1, color="#404788FF", label="τ=2.0")
    plot!(datatau2ua.a[20:end], datatau2ua.N1[20:end], color="#404788FF", linestyle=:dash, lw=1.5, label="")
    plot!(datatau4s.a, datatau4s.N1, color="#1F968BFF", label="τ=4.0")
    plot!(datatau4ua.a[40:end], datatau4ua.N1[40:end], color="#1F968BFF", linestyle=:dash, lw=1.5, label="")
    plot!(datatau6s.a, datatau6s.N1, color="#73D055FF", label="τ=6.0")
    plot!(datatau6ua.a[40:end], datatau6ua.N1[40:end], color="#73D055FF", linestyle=:dash, lw=1.5, label="")
    xlabel!("a")
    ylabel!("N*(a)")
    ylims!(-0.9, 20.0)
    yticks
    xlims!(0.0, 5.0)
    plot!(legend=false, left_margin=10mm)
    annotate!([-2.5],[19], ("a)", 18, "Computer Modern"))
    p2=plot(datatau2s.a, datatau2s.N1, color="#404788FF", label="\$\\tau\$=2.0")
    plot!(datatau2ua.a[20:end], datatau2ua.N1[20:end], color="#404788FF", linestyle=:dash, lw=1.5, label="")
    plot!(datatau4s.a, datatau4s.N1, color="#1F968BFF", label="\$\\tau\$=4.0")
    plot!(datatau4ua.a[20:end], datatau4ua.N1[20:end], color="#1F968BFF", linestyle=:dash, lw=1.5, label="")
    plot!(datatau6s.a, datatau6s.N1, color="#73D055FF", label="\$\\tau\$=6.0")
    plot!(maxmindata2.a, maxmindata2.maximum, color="#404788FF", linestyle=:dashdotdot, lw=2, label="")
    plot!(maxmindata2.a, maxmindata2.minimum, color="#404788FF", linestyle=:dashdotdot,lw=2, label="")
    plot!(maxmindata4.a, maxmindata4.maximum, color="#1F968BFF", linestyle=:dashdotdot,lw=2, label="")
    plot!(maxmindata4.a, maxmindata4.minimum, color="#1F968BFF", linestyle=:dashdotdot,lw=2, label="")
    plot!(maxmindata6.a, maxmindata6.maximum, color="#73D055FF", linestyle=:dashdotdot,lw=2, label="")
    plot!(maxmindata6.a, maxmindata6.minimum, color="#73D055FF", linestyle=:dashdotdot,lw=2, label="")
    plot!([-1], [0], linestyle=:solid, color=:black, label="Stable")
    plot!([-1], [0], linestyle=:dash, color=:black, lw=1.5, label="Unstable")
    plot!([-1], [0], linestyle=:dashdotdot, color=:black,lw=2, label="N-S max/min")
    xlabel!("a")
    ylims!(-0.9, 20.0)
    xlims!(10.0, 15.0)
    plot!(yaxis=false, left_margin=-5mm)
    p3=plot(datatau6s.a, datatau6s.N1, color="#73D055FF", label="\$\\tau\$=6.0")
    plot!(datatau6ua.a[30:end], datatau6ua.N1[30:end], color="#73D055FF", linestyle=:dash, lw=1.5, label="")
    plot!(maxmindata6.a, maxmindata6.maximum, color="#73D055FF", linestyle=:dashdotdot,lw=2, label="")
    plot!(maxmindata6.a, maxmindata6.minimum, color="#73D055FF", linestyle=:dashdotdot,lw=2, label="")
    plot!([32, 32], [0.0, findRCvalue(datatau6, 32.0, "stable")], color=:black, linestyle=:solid, lw=1, label="")
    plot!([33, 33], [0.0, findRCvalue(maxmindata6, 33.0, "max")], color=:black, linestyle=:solid, lw=1, label="")
    scatter!([32],[-0.5],color=:black,marker=:star5,ms=8,label="")
    scatter!([33],[-0.5],color=:black,ms=5,label="")
    xlabel!("a")
    ylims!(-0.9, 20.0)
    xlims!(30.0, 36.0)
    xticks!([30, 32, 34, 36])
    plot!(legend=false,yaxis=false, left_margin=-5mm)
    p4=scatter(merged_dfs.N, merged_dfs.N_1, color=:black, label="Fixed Point", ms=8, marker=:star5)
    scatter!(merged_df.N, merged_df.N_1, color=:black, label="N-S", ms=3)
    xlabel!("N(t-\$\\tau\$)")
    ylabel!("N(t)")
    ylims!(-0.9,20)
    annotate!([-4],[19], ("b)", 18, "Computer Modern"))
    plot!(legend=:bottomleft,left_margin=6mm)
    plot(p1, p2,p3,p4, layout = @layout([a{0.15w} b{0.35w} c{0.15w} d{0.3w}]), size = (1200, 400), bottom_margin=10mm)
    savefig(joinpath(abpath(), "figs/RickerConstanttaueven.svg"))
end

let #tau=3 (odd)
    datatau3 = cleanxppautdat_onepar("src/xppaut/RickerConstanttau3_a.dat")
    tau3lowerbound = alowerconstraint(RickerPar(p=0.6, τ=3.0, α=0.1, β=0.3, b=200, K=1.0))
    tau3upperbound = ahigherconstraint(RickerPar(p=0.6, τ=3.0, α=0.1, β=0.3, b=200, K=1.0))
    datatau3_filtered = @subset(datatau3, :a .> tau3lowerbound)
    datatau3s1 = @subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 1.0)
    datatau3s2p2upper = unique(@subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 2.0 .&& :N1 .> maximum(datatau3s1.N1)), :a)
    datatau3s2p2lower = unique(@subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 2.0 .&& :N1 .< maximum(datatau3s1.N1) .&& :N1 .> 0.1), :a)
    datatau3s2_0 = @subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 2.0 .&& :N1 .< 1.00)
    datatau3s3p4upperupper = @subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 3.0 .&& :N1 .> maximum(datatau3s2p2upper.N1))
    datatau3s3p4upperlower = @subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 3.0 .&& :N1 .< maximum(datatau3s2p2upper.N1) .&& :N1 .> 0.1)
    datatau3s3p4lowerupper = unique(@subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 4.0 .&& :N1 .< maximum(datatau3s2p2lower.N1)), :a)
    datatau3s3p4lowerlower = @subset(datatau3_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 4.0 .&& :N1 .< minimum(datatau3s2p2lower.N1) .&& :N1 .> 0.1)
    datatau3u1 = unique(@subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :a .> 7 .&& :LineNum .== 1.0 .&& :N1 .> 0.00), :a)
    datatau3u2upper = @subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 2.0 .&& :N1 .> maximum(datatau3s1.N1) .&& :a .> maximum(datatau3s1.a) + 0.1)
    datatau3u2lower = @subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 2.0 .&& :N1 .< maximum(datatau3s1.N1) .&& :N1 .> 0 .&& :a .> maximum(datatau3s1.a) + 0.1)
    datatau3u3 = branchsplitter(@subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :a .> 7.00 .&& :LineNum .== 3.0 .&& :N1 .> 0.00))
    datatau3u4upper = @subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :a .> 7.00 .&& :LineNum .== 4.0 .&& :N1 .> maximum(datatau3s3p4lowerlower.N1))
    datatau3u4lower = @subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :a .> 7.00 .&& :LineNum .== 4.0 .&& :N1 .< maximum(datatau3s3p4lowerlower.N1) .&& :N1 .> 0.001)
    datatau3u0 = @subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 2.0 .&& :N1 .< 0.001)
    datatau3ul0 = @subset(datatau3_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 1.0 .&& :N1 .< 0.001)
    #Time embedding prep
        endtime = 1000000
    finalts = 999000
    timeseriesp4 = model_recursion(0.1, endtime, RickerPar(τ=3, p=0.6, a=10.92, α=0.1, β=0.3, K=1.0, b=200), RickerConstant_model)
    dfp4 = DataFrame(time = 0:endtime, N = timeseriesp4)
    dfp4.periodpoint = mod.(dfp4.time, 4) .+ 1
    dfp4.periodpoint = map(x -> x == 1 ? 3 : x == 2 ? 4 : x == 3 ? 1 : x == 4 ? 2 : x, dfp4.periodpoint)
    dfxaxisp4 = @subset(dfp4, :time .>= finalts-3 .&& :time .<= endtime-3)
    select!(dfxaxisp4, Not(:periodpoint))
    dfyaxisp4 = @subset(dfp4, :time .>= finalts)
    dfxaxisp4.row = 1:nrow(dfxaxisp4)
    dfyaxisp4.row = 1:nrow(dfyaxisp4)
    merged_dfp4 = leftjoin(dfxaxisp4, dfyaxisp4, on=:row, makeunique=true)
    select!(merged_dfp4, Not([:time, :time_1, :row]))
    df1p4 = @subset(merged_dfp4, :periodpoint .== 1)
    df2p4 = @subset(merged_dfp4, :periodpoint .== 2)
    df3p4 = @subset(merged_dfp4, :periodpoint .== 3)
    df4p4 = @subset(merged_dfp4, :periodpoint .== 4)
    timeseries = model_recursion(0.1, endtime, RickerPar(τ=3, p=0.6, a=11.04, α=0.1, β=0.3, K=1.0, b=200), RickerConstant_model)
    df = DataFrame(time = 0:endtime, N = timeseries)
    df.periodpoint = mod.(df.time, 4) .+ 1
    dfxaxis = @subset(df, :time .>= finalts-3 .&& :time .<= endtime-3)
    select!(dfxaxis, Not(:periodpoint))
    dfyaxis = @subset(df, :time .>= finalts)
    dfxaxis.row = 1:nrow(dfxaxis)
    dfyaxis.row = 1:nrow(dfyaxis)
    merged_df = leftjoin(dfxaxis, dfyaxis, on=:row, makeunique=true)
    select!(merged_df, Not([:time, :time_1, :row]))
    df1 = @subset(merged_df, :periodpoint .== 1)
    df2 = @subset(merged_df, :periodpoint .== 2)
    df3 = @subset(merged_df, :periodpoint .== 3)
    df4 = @subset(merged_df, :periodpoint .== 4)

    p1=plot(datatau3s1.a, datatau3s1.N1, color=:black, label="Stable")
    plot!(datatau3s2_0.a, datatau3s2_0.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3u0.a, datatau3u0.N1, color=:black, linestyle=:dash, lw=2, label="")
    plot!(datatau3ul0.a, datatau3ul0.N1, color=:black, linestyle=:dash, lw=2, label="")
    ylabel!("N*(a)")
    xlabel!("a")
    xticks!([4, 5, 6])
    xlims!(tau3lowerbound, 6.0)
    ylims!(-1, 30.0)
    plot!([tau3lowerbound, tau3lowerbound], [-1, 30], color=:black, linestyle=:solid, lw=1.5, label="")
    plot!(legend=false, left_margin=10mm)
    annotate!([2.5],[29],("a)",18,"Computer Modern"))
    p2=plot(datatau3s1.a, datatau3s1.N1, color=:black, label="Stable")
    plot!(datatau3s2p2upper.a, datatau3s2p2upper.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3s2p2lower.a, datatau3s2p2lower.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3s2_0.a, datatau3s2_0.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3s3p4upperupper.a, datatau3s3p4upperupper.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3s3p4upperlower.a, datatau3s3p4upperlower.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3s3p4lowerupper.a, datatau3s3p4lowerupper.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3s3p4lowerlower.a, datatau3s3p4lowerlower.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau3u1.a[20:end], datatau3u1.N1[20:end], color=:black, linestyle=:dash, lw=1.5, label="Unstable")
    plot!(datatau3u2upper.a[40:end], datatau3u2upper.N1[40:end], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau3u2lower.a[40:end], datatau3u2lower.N1[40:end], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau3u3[1].a[40:end], datatau3u3[1].N1[40:end], color=:black, linestyle=:dash, lw=1.5, label="")

    plot!(datatau3u3[2].a[40:end], datatau3u3[2].N1[40:end], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau3u4upper.a[40:end-2], datatau3u4upper.N1[40:end-2], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau3u4lower.a[40:end], datatau3u4lower.N1[40:end], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau3u0.a, datatau3u0.N1, color=:black, linestyle=:dash, lw=2, label="")
    plot!(datatau3ul0.a, datatau3ul0.N1, color=:black, linestyle=:dash, lw=2, label="")
    xlabel!("a")
    xlims!(10.0, tau3upperbound + 0.1)
    xticks!([10,10.5, 11])
    ylims!(-1, 30.0)
    plot!([11.04, 11.04], [0.0, findRCvalue(datatau3u3[1], 11.04, "unstable")], color=:black, linestyle=:solid, lw=1, label="")
    plot!([10.92, 10.92], [0.0, findRCvalue(datatau3s3p4upperupper, 10.92, "stable")], color=:black, linestyle=:solid, lw=1, label="")
    scatter!([10.92],[-0.5],color=:black,marker=:star5,ms=8,label="")
    scatter!([11.04],[-0.5],color=:black,ms=5,label="")
    plot!(yaxis=false, left_margin=-5mm)
    p3=scatter(df1.N, df1.N_1, color="#FDE725FF", label="1", ms=2.5,markerstrokewidth=0)
    scatter!(df2.N, df2.N_1, color="#73D055FF", label="2", ms=2.5,markerstrokewidth=0)
    scatter!(df3.N, df3.N_1, color="#238A8DFF", label="3", ms=2.5,markerstrokewidth=0)
    scatter!(df4.N, df4.N_1, color="#440154FF", label="4", ms=2.5,markerstrokewidth=0)
    scatter!(df1p4.N, df1p4.N_1, color="#FDE725FF", label="", ms=8, marker=:star5,markerstrokewidth=0)
    scatter!(df2p4.N, df2p4.N_1, color="#73D055FF", label="", ms=8, marker=:star5,markerstrokewidth=0)
    scatter!(df3p4.N, df3p4.N_1, color="#238A8DFF", label="", ms=8, marker=:star5,markerstrokewidth=0)
    scatter!(df4p4.N, df4p4.N_1, color="#440154FF", label="", ms=8, marker=:star5,markerstrokewidth=0)
    scatter!([NaN], [NaN], colour=:black,marker=:star5, label="Period Four")
    scatter!([NaN], [NaN], colour=:black, marker=:circle, label="N-S")
    xlabel!("N(t-\$\\tau\$)")
    ylabel!("N(t)")
    ylims!(-1,30.0)
    annotate!([-7],[29],("b)",18,"Computer Modern"))
    plot(p1, p2,p3, layout = @layout([a{0.15w} b{0.55w} c{0.3w}]), size = (1200, 400), bottom_margin=10mm)
    savefig(joinpath(abpath(), "figs/RickerConstanttau3.pdf"))
end

datatau5 = cleanxppautdat_onepar("src/xppaut/RickerConstanttau5_a.dat")
negN1_unstable_linenum = unique(@subset(datatau5, :N1 .< 0 .&& :PointTypeName .== "Unstable").LineNum)
println("LineNum values where N1 < 0 and PointTypeName == \"Unstable\": ", negN1_unstable_linenum)

let #tau=5 (odd)
    datatau5 = cleanxppautdat_onepar("src/xppaut/RickerConstanttau5_a.dat")
    tau5lowerbound = alowerconstraint(RickerPar(p=0.6, τ=5.0, α=0.1, β=0.3, b=200, K=1.0))
    tau5upperbound = ahigherconstraint(RickerPar(p=0.6, τ=5.0, α=0.1, β=0.3, b=200, K=1.0))
    datatau5_filtered = sort(@subset(datatau5, :a .> tau5lowerbound), :a)
    datatau5s1 = @subset(datatau5_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 1.0)
    datatau5s2pupper = unique(@subset(datatau5_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 2.0 .&& :N1 .> maximum(datatau5s1.N1)), :a)
    datatau5s2plower = unique(@subset(datatau5_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 2.0 .&& :N1 .< maximum(datatau5s1.N1) .&& :N1 .> 0.1), :a)
    datatau5s2_0 = @subset(datatau5_filtered, :PointTypeName .== "Stable" .&& :LineNum .== 2.0 .&& :N1 .< 1.00)

    datatau5u1 = unique(@subset(datatau5_filtered, :PointTypeName .== "Unstable" .&& :a .> 15 .&& :LineNum .== 1.0 .&& :N1 .> 0.00), :a)
    datatau5u1l = unique(@subset(datatau5_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 1.0 .&& :N1 .< 0.00), :a)

    datatau5u2pupper = @subset(datatau5_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 2.0 .&& :N1 .> maximum(datatau5s1.N1) .&& :a .> maximum(datatau5s1.a) + 0.1)
    datatau5u2plower = @subset(datatau5_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 2.0 .&& :N1 .< maximum(datatau5s1.N1) .&& :N1 .> 0 .&& :a .> maximum(datatau5s1.a) + 0.1)
    datatau5u0 = @subset(datatau5_filtered, :PointTypeName .== "Unstable" .&& :LineNum .== 2.0 .&& :N1 .< 0.001)
    #Time embedding prep
    endtime = 1000000
    finalts = 999000
    timeseriesp2 = model_recursion(0.1, endtime, RickerPar(τ=5, p=0.6, a=20.4, α=0.1, β=0.3, K=1.0, b=200), RickerConstant_model)
    dfp2 = DataFrame(time = 0:endtime, N = timeseriesp2)
    dfp2.periodpoint = mod.(dfp2.time, 2) .+ 1
    dfxaxisp2 = @subset(dfp2, :time .>= finalts-5 .&& :time .<= endtime-5)
    select!(dfxaxisp2, Not(:periodpoint))
    dfyaxisp2 = @subset(dfp2, :time .>= finalts)
    dfxaxisp2.row = 1:nrow(dfxaxisp2)
    dfyaxisp2.row = 1:nrow(dfyaxisp2)
    merged_dfp2 = leftjoin(dfxaxisp2, dfyaxisp2, on=:row, makeunique=true)
    select!(merged_dfp2, Not([:time, :time_1, :row]))
    df1p2 = @subset(merged_dfp2, :periodpoint .== 1)
    df2p2 = @subset(merged_dfp2, :periodpoint .== 2)
    timeseries = model_recursion(0.1, endtime, RickerPar(τ=5, p=0.6, a=20.7, α=0.1, β=0.3, K=1.0, b=200), RickerConstant_model)
    df = DataFrame(time = 0:endtime, N = timeseries)
    df.periodpoint = mod.(df.time, 2) .+ 1
    dfxaxis = @subset(df, :time .>= finalts-5 .&& :time .<= endtime-5)
    select!(dfxaxis, Not(:periodpoint))
    dfyaxis = @subset(df, :time .>= finalts)
    dfxaxis.row = 1:nrow(dfxaxis)
    dfyaxis.row = 1:nrow(dfyaxis)
    merged_df = leftjoin(dfxaxis, dfyaxis, on=:row, makeunique=true)
    select!(merged_df, Not([:time, :time_1, :row]))
    df1 = @subset(merged_df, :periodpoint .== 1)
    df2 = @subset(merged_df, :periodpoint .== 2)

    p1=plot(datatau5s1.a, datatau5s1.N1, color=:black, label="Stable")
    plot!(datatau5s2_0.a, datatau5s2_0.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau5u0.a, datatau5u0.N1, color=:black, linestyle=:dash, lw=2, label="")
    plot!(datatau5u1l.a, datatau5u1l.N1, color=:black, linestyle=:dash, lw=2, label="")
    plot!([20.2, 20.2], [-0.5, findRCvalue(datatau5s2pupper, 20.2, "stable")], color=:black, linestyle=:dash, lw=1, label="")
    plot!([20.7, 20.7], [-0.5, findRCvalue(datatau5u2pupper, 20.7, "unstable")], color=:black, linestyle=:dash, lw=1, label="")
    ylabel!("N*(a)")
    xlabel!("a")
    xlims!(0.0, 6.0)
    xticks!([0, 2, 4, 6])
    ylims!(-1, 30.0)
    plot!(legend=false, left_margin=10mm)
    annotate!([-2.5],[29],("a)",18,"Computer Modern"))
    p2=plot(datatau5s1.a, datatau5s1.N1, color=:black, label="Stable")
    plot!(datatau5s2pupper.a, datatau5s2pupper.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau5s2plower.a, datatau5s2plower.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau5s2_0.a, datatau5s2_0.N1, color=:black, linestyle=:solid, label="")
    plot!(datatau5u1.a[10:end], datatau5u1.N1[10:end], color=:black, linestyle=:dash, lw=1.5, label="Unstable")
    plot!(datatau5u2pupper.a[20:end], datatau5u2pupper.N1[20:end], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau5u2plower.a[20:end], datatau5u2plower.N1[20:end], color=:black, linestyle=:dash, lw=1.5, label="")
    plot!(datatau5u0.a, datatau5u0.N1, color=:black, linestyle=:dash, lw=2, label="")
    plot!([20.4, 20.4], [0, findRCvalue(datatau5s2pupper, 20.4, "stable")], color=:black, linestyle=:solid, lw=1, label="")
    plot!([20.7, 20.7], [0, findRCvalue(datatau5u2pupper, 20.7, "unstable")], color=:black, linestyle=:solid, lw=1, label="")
    scatter!([20.4],[-0.5],color=:black,marker=:star5,ms=8,label="")
    scatter!([20.7],[-0.5],color=:black,ms=5,label="")
    xlabel!("a")
    xlims!(18.0, tau5upperbound + 0.1)
    ylims!(-1, 30.0)
    plot!(yaxis=false, left_margin=-5mm)
    p3=scatter(df1.N, df1.N_1, color="#FDE725FF", label="1", ms=2.5,markerstrokewidth=0)
    scatter!(df2.N, df2.N_1, color="#73D055FF", label="2", ms=2.5,markerstrokewidth=0)
    scatter!(df1p2.N, df1p2.N_1, color="#FDE725FF", label="", ms=8, marker=:star5,markerstrokewidth=0)
    scatter!(df2p2.N, df2p2.N_1, color="#73D055FF", label="", ms=8, marker=:star5,markerstrokewidth=0)
    scatter!([NaN], [NaN], colour=:black,marker=:star5, label="Period Two")
    scatter!([NaN], [NaN], colour=:black, marker=:circle, label="N-S")
    xlabel!("N(t-\$\\tau\$)")
    ylabel!("N(t)")
    ylims!(-1,30.0)
    annotate!([-5.],[29],("b)",18,"Computer Modern"))
    plot(p1, p2, p3, layout = @layout([a{0.15w} b{0.55w} c{0.3w}]), size = (1200, 400), bottom_margin=10mm)
    savefig(joinpath(abpath(), "figs/RickerConstanttau5.pdf"))
end

let #2 parameter (a & p) bifurcation diagram of Ricker Constant 
    datatau1 = cleanxppautdat_twopar("src/xppaut/RickerConstanttau1.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar)
    datatau2 = cleanxppautdat_twopar("src/xppaut/RickerConstanttau2.dat")
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat_twopar("src/xppaut/RickerConstanttau3.dat")
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat_twopar("src/xppaut/RickerConstanttau4.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau8 = cleanxppautdat_twopar("src/xppaut/RickerConstanttau8.dat")
    bp_datatau8 = unique(@subset(datatau8, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau8 = unique(@subset(datatau8, :PointTypeName .== "HP"), :Low2ndpar)

    p1=plot(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2.75, linestyle=:solid, color="#440154FF", label="\$\\tau\$=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2.75, linestyle=:dash, color="#440154FF", label="")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2.75, linestyle=:solid, color="#39568CFF", label="\$\\tau\$=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2.75, linestyle=:dash, color="#39568CFF", label="")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2.75, linestyle=:solid, color="#1F968BFF", label="\$\\tau\$=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2.75, linestyle=:dash, color="#1F968BFF", label="")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2.75, linestyle=:solid, color="#73D055FF", label="\$\\tau\$=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2.75, linestyle=:dash, color="#73D055FF", label="")
    plot!(bp_datatau8.a, bp_datatau8.Low2ndpar, lw=2.75, linestyle=:solid, color="#FDE725FF", label="\$\\tau\$=8")
    plot!(hp_datatau8.a, hp_datatau8.Low2ndpar, lw=2.75, linestyle=:dash, color="#FDE725FF", label="")
    plot!([NaN], [NaN], lw=2, linestyle=:solid, color=:black, label="Transcritical")
    plot!([NaN], [NaN], lw=2, linestyle=:dash, color=:black, label="Oscillations")
    scatter!([13.0], [0.57205], color=:black, marker=:star5, ms=10, label="")
    scatter!([13.0], [0.35], color=:black, marker=:square, ms=6, label="")
    xlims!(0.0, 40.0)
    ylims!(0.0, 1.0)
    xlabel!("a")
    ylabel!("\${\\overline{p}}\$")
    annotate!([-5],[0.99],("a)", 18, "Computer Modern"))
    plot!(legend=:outerleft)

    plot!(size = (800, 400),bottom_margin=5mm)
    savefig(joinpath(abpath(), "figs/RickerConstant_apbifurcation.svg"))
end

let 
    #Orbit diagrams prep
    par1 = RickerPar(a=13.0, p=0.57205, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RCorbitdata1 = flattenorbitdata(orbitdiagrams(RickerConstant_model, "τ", par1, 50; optτ=2, upperval=8))
    par2 = RickerPar(a=13.0, p=0.35, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RCorbitdata2 = flattenorbitdata(orbitdiagrams(RickerConstant_model, "τ", par2, 50; upperval=8))
    
    p1=scatter(RCorbitdata1[1], log10.(RCorbitdata1[2] .+1), color=:black, ms=4,label="")
    scatter!([1.0], [0.0], color=:black, ms=4, label="")
    xlabel!("\$\\tau\$")
    ylabel!("\$\\log_{10}(N+1)\$")
    xticks!([0, 2, 4, 6, 8])
    xlims!(0.0, 8.5)
    annotate!([-3],[3.9],("b)", 18, "Computer Modern"))
    plot!(top_margin=5mm)

    p2 = scatter(RCorbitdata2[1], RCorbitdata2[2], color=:black, ms=4, label="")
    scatter!([1.0], [0.0], color=:black, ms=4,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    xlims!(0.0, 8.5)
    xticks!([0, 2, 4, 6, 8])
    annotate!([-3],[0.18],("c)", 18, "Computer Modern"))
    plot!(p1,p2,layout=(2,1), size=(325,400), left_margin=5mm)
    savefig(joinpath(abpath(), "figs/RickerConstant_apbifurcation_tauorbits.svg"))

end

#BevertonHoltBevertonHolt model
let 
    τrange = 1:1:15
    Cval01data=NdataBHBH("C", τrange, 0.1, BevHoltPar(α=0.3,β=0.3,D=0.3,a=5.0,b=200.0,K=1.0))
    Cval03data=NdataBHBH("C", τrange, 0.3, BevHoltPar(α=0.3,β=0.3,D=0.3,a=5.0,b=200.0,K=1.0))
    Cval06data=NdataBHBH("C", τrange, 0.6, BevHoltPar(α=0.3,β=0.3,D=0.3,a=5.0,b=200.0,K=1.0))
    Dval01data=NdataBHBH("D", τrange, 0.1, BevHoltPar(α=0.3,C=0.3,β=0.3,a=5.0,b=200.0,K=1.0))
    Dval03data=NdataBHBH("D", τrange, 0.3, BevHoltPar(α=0.3,C=0.3,β=0.3,a=5.0,b=200.0,K=1.0))
    Dval06data=NdataBHBH("D", τrange, 0.6, BevHoltPar(α=0.3,C=0.3,β=0.3,a=5.0,b=200.0,K=1.0))
    βval01data=NdataBHBH("β", τrange, 0.1, BevHoltPar(α=0.3,C=0.3,D=0.3,a=5.0,b=200.0,K=1.0))
    βval03data=NdataBHBH("β", τrange, 0.3, BevHoltPar(α=0.3,C=0.3,D=0.3,a=5.0,b=200.0,K=1.0))
    βval06data=NdataBHBH("β", τrange, 0.6, BevHoltPar(α=0.3,C=0.3,D=0.3,a=5.0,b=200.0,K=1.0))
    αval01data=NdataBHBH("α", τrange, 0.1, BevHoltPar(C=0.3,D=0.3,β=0.3,a=5.0,b=200.0,K=1.0))
    αval03data=NdataBHBH("α", τrange, 0.3, BevHoltPar(C=0.3,D=0.3,β=0.3,a=5.0,b=200.0,K=1.0))
    αval06data=NdataBHBH("α", τrange, 0.6, BevHoltPar(C=0.3,D=0.3,β=0.3,a=5.0,b=200.0,K=1.0))
    p1=scatter(τrange .+ randn(length(τrange)) .* 0.05, Cval01data, color="#FDE725FF",markersize=6,markerstrokewidth=0,label="C=0.1")
    plot!(collect(1:1:15), Cval01data, label="",linestyle=:dash, color="#FDE725FF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, Cval03data, color="#238A8DFF", markersize=6,markerstrokewidth=0,label="C=0.3")
    plot!(collect(1:1:15), Cval03data, label="",linestyle=:dash, color="#238A8DFF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, Cval06data, color="#440154FF", markersize=6,markerstrokewidth=0,label="C=0.6")
    plot!(collect(1:1:15), Cval06data, label="",linestyle=:dash, color="#440154FF")
    xlabel!("\$\\tau\$")
    ylabel!("N*(\$\\tau\$)")
    ylims!(0,1.5)
    p2=scatter(τrange .+ randn(length(τrange)) .* 0.05, Dval01data, color="#FDE725FF",markersize=6,markerstrokewidth=0, label="D=0.1")
    plot!(collect(1:1:15), Dval01data, label="",linestyle=:dash, color="#FDE725FF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, Dval03data, color="#238A8DFF", markersize=6,markerstrokewidth=0,label="D=0.3")
    plot!(collect(1:1:15), Dval03data, label="",linestyle=:dash, color="#238A8DFF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, Dval06data, color="#440154FF", markersize=6,markerstrokewidth=0,label="D=0.6")
    plot!(collect(1:1:15), Dval06data, label="",linestyle=:dash, color="#440154FF")
    xlabel!("\$\\tau\$")
    ylabel!("N*(\$\\tau\$)")
    ylims!(0,1.5)
    p3=scatter(τrange .+ randn(length(τrange)) .* 0.05, βval01data, color="#FDE725FF",markersize=6,markerstrokewidth=0, label="β=0.1")
    plot!(collect(1:1:15), βval01data, label="",linestyle=:dash, color="#FDE725FF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, βval03data, color="#238A8DFF", markersize=6,markerstrokewidth=0,label="β=0.3")
    plot!(collect(1:1:15), βval03data, label="",linestyle=:dash, color="#238A8DFF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, βval06data, color="#440154FF", markersize=6,markerstrokewidth=0,label="β=0.6")
    plot!(collect(1:1:15), βval06data, label="",linestyle=:dash, color="#440154FF")
    xlabel!("\$\\tau\$")
    ylabel!("N*(\$\\tau\$)")
    ylims!(0,1.5)
    p4=scatter(τrange .+ randn(length(τrange)) .* 0.05, αval01data, color="#FDE725FF",markersize=6,markerstrokewidth=0, label="α=0.1")
    plot!(collect(1:1:15), αval01data, label="",linestyle=:dash, color="#FDE725FF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, αval03data, color="#238A8DFF", markersize=6,markerstrokewidth=0,label="α=0.3")
    plot!(collect(1:1:15), αval03data, label="",linestyle=:dash, color="#238A8DFF")
    scatter!(τrange .+ randn(length(τrange)) .* 0.05, αval06data, color="#440154FF", markersize=6,markerstrokewidth=0,label="α=0.6")
    plot!(collect(1:1:15), αval06data, label="",linestyle=:dash, color="#440154FF")
    xlabel!("\$\\tau\$")
    ylabel!("N*(\$\\tau\$)")
    ylims!(0,1.5)
    plot(p1, p2,p3,p4, layout=(2,2), size=(800,800), legend=:topright)
    savefig(joinpath(abpath(), "figs/BevHoltBevHolt_tauequi.pdf"))
end


#RickerRicker
#a and C/β two par bifurcation figure
let
    datatau1C = cleanxppautdat_twopar("src/xppaut/RickerRickertau1_C.dat")
    bp_datatau1C = unique(@subset(datatau1C, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1C = unique(@subset(datatau1C, :PointTypeName .== "HP"), :Low2ndpar)
    datatau2C = cleanxppautdat_twopar("src/xppaut/RickerRickertau2_C.dat")
    bp_datatau2C = unique(@subset(datatau2C, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2C = unique(@subset(datatau2C, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3C = cleanxppautdat_twopar("src/xppaut/RickerRickertau3_C.dat")
    bp_datatau3C = unique(@subset(datatau3C, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3C = unique(@subset(datatau3C, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4C = cleanxppautdat_twopar("src/xppaut/RickerRickertau4_C.dat")
    bp_datatau4C = unique(@subset(datatau4C, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4C = unique(@subset(datatau4C, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5C = cleanxppautdat_twopar("src/xppaut/RickerRickertau5_C.dat")
    bp_datatau5C = unique(@subset(datatau5C, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5C = unique(@subset(datatau5C, :PointTypeName .== "HP"), :Low2ndpar)
    datatau9C = cleanxppautdat_twopar("src/xppaut/RickerRickertau9_C.dat")
    bp_datatau9C = unique(@subset(datatau9C, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau9C = unique(@subset(datatau9C, :PointTypeName .== "HP"), :Low2ndpar)
    datatau1β = cleanxppautdat_twopar("src/xppaut/RickerRickertau1_beta_b.dat")
    bp_datatau1β = unique(@subset(datatau1β, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1β = unique(@subset(datatau1β, :PointTypeName .== "HP" .&& :a .<= 70), :Low2ndpar)
    datatau2β = cleanxppautdat_twopar("src/xppaut/RickerRickertau2_beta_b.dat")
    bp_datatau2β = unique(@subset(datatau2β, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2β = unique(@subset(datatau2β, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3β = cleanxppautdat_twopar("src/xppaut/RickerRickertau3_beta_b.dat")
    bp_datatau3β = unique(@subset(datatau3β, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3β = unique(@subset(datatau3β, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4β = cleanxppautdat_twopar("src/xppaut/RickerRickertau4_beta_b.dat")
    bp_datatau4β = unique(@subset(datatau4β, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4β = unique(@subset(datatau4β, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5β = cleanxppautdat_twopar("src/xppaut/RickerRickertau5_beta_b.dat")
    bp_datatau5β = unique(@subset(datatau5β, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5β = unique(@subset(datatau5β, :PointTypeName .== "HP"), :Low2ndpar)
    datatau9β = cleanxppautdat_twopar("src/xppaut/RickerRickertau9_beta_b.dat")
    bp_datatau9β = unique(@subset(datatau9β, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau9β = unique(@subset(datatau9β, :PointTypeName .== "HP"), :Low2ndpar)
    
    p1=plot(bp_datatau1C.a, bp_datatau1C.Low2ndpar, lw=3.5, linestyle=:solid, color="#440154FF", label="\$\\tau\$=1")
    plot!(hp_datatau1C.a, hp_datatau1C.Low2ndpar, lw=3.5, linestyle=:dash, color="#440154FF", label="")
    plot!(bp_datatau2C.a, bp_datatau2C.Low2ndpar, lw=3.5, linestyle=:solid, color="#404788FF", label="\$\\tau\$=2")
    plot!(hp_datatau2C.a, hp_datatau2C.Low2ndpar, lw=3.5, linestyle=:dash, color="#404788FF", label="")
    plot!(bp_datatau3C.a, bp_datatau3C.Low2ndpar, lw=3.5, linestyle=:solid, color="#2D708EFF", label="\$\\tau\$=3")
    plot!(hp_datatau3C.a, hp_datatau3C.Low2ndpar, lw=3.5, linestyle=:dash, color="#2D708EFF", label="")
    plot!(bp_datatau4C.a, bp_datatau4C.Low2ndpar, lw=3.5, linestyle=:solid, color="#20A387FF", label="\$\\tau\$=4")
    plot!(hp_datatau4C.a, hp_datatau4C.Low2ndpar, lw=3.5, linestyle=:dash, color="#20A387FF", label="")
    plot!(bp_datatau5C.a, bp_datatau5C.Low2ndpar, lw=3.5, linestyle=:solid, color="#73D055FF", label="\$\\tau\$=5")
    plot!(hp_datatau5C.a, hp_datatau5C.Low2ndpar, lw=3.5, linestyle=:dash, color="#73D055FF", label="")
    plot!(bp_datatau9C.a, bp_datatau9C.Low2ndpar, lw=3.5, linestyle=:solid, color="#FDE725FF", label="\$\\tau\$=9")
    plot!(hp_datatau9C.a, hp_datatau9C.Low2ndpar, lw=3.5, linestyle=:dash, color="#FDE725FF", label="")
    scatter!([26.5], [0.5], color=:black, marker=:star5, ms=10, label="")
    scatter!([26.5], [0.1], color=:black, marker=:square, ms=6, label="")
    scatter!([26.5], [0.3], color=:black, marker=:diamond, ms=8, label="")
    plot!([NaN], [NaN], lw=2, linestyle=:solid, color=:black, label="Transcritical")
    plot!([NaN], [NaN], lw=2, linestyle=:dash, color=:black, label="N-S")
    xlims!(0.0, 50.0)
    ylims!(0.0, 0.8)
    xlabel!("a")
    ylabel!("C")
    annotate!([-8.5],[0.75],("a)", 18, "Computer Modern"))
    plot!(left_margin=8mm,legend=false)
    p2=plot(bp_datatau1β.a, bp_datatau1β.Low2ndpar, lw=3.5, linestyle=:solid, color="#440154FF", label="\$\\tau\$=1")
    plot!(hp_datatau1β.a, hp_datatau1β.Low2ndpar, lw=3.5, linestyle=:dash, color="#440154FF", label="")
    plot!(bp_datatau2β.a, bp_datatau2β.Low2ndpar, lw=3.5, linestyle=:solid, color="#404788FF", label="\$\\tau\$=2")
    plot!(hp_datatau2β.a, hp_datatau2β.Low2ndpar, lw=3.5, linestyle=:dash, color="#404788FF", label="")
    plot!(bp_datatau3β.a, bp_datatau3β.Low2ndpar, lw=3.5, linestyle=:solid, color="#2D708EFF", label="\$\\tau\$=3")
    plot!(hp_datatau3β.a, hp_datatau3β.Low2ndpar, lw=3.5, linestyle=:dash, color="#2D708EFF", label="")
    plot!(bp_datatau4β.a, bp_datatau4β.Low2ndpar, lw=3.5, linestyle=:solid, color="#20A387FF", label="\$\\tau\$=4")
    plot!(hp_datatau4β.a, hp_datatau4β.Low2ndpar, lw=3.5, linestyle=:dash, color="#20A387FF", label="")
    plot!(bp_datatau5β.a, bp_datatau5β.Low2ndpar, lw=3.5, linestyle=:solid, color="#73D055FF", label="\$\\tau\$=5")
    plot!(hp_datatau5β.a, hp_datatau5β.Low2ndpar, lw=3.5, linestyle=:dash, color="#73D055FF", label="")
    plot!(bp_datatau9β.a, bp_datatau9β.Low2ndpar, lw=3.5, linestyle=:solid, color="#FDE725FF", label="\$\\tau\$=9")
    plot!(hp_datatau9β.a, hp_datatau9β.Low2ndpar, lw=3.5, linestyle=:dash, color="#FDE725FF", label="")
    scatter!([26.5], [0.5], color=:black, marker=:star5, ms=10, label="")
    scatter!([26.5], [0.1], color=:black, marker=:square, ms=6, label="")
    scatter!([26.5], [0.3], color=:black, marker=:diamond, ms=8, label="")

    plot!([NaN], [NaN], lw=2, linestyle=:solid, color=:black, label="Transcritical")
    plot!([NaN], [NaN], lw=2, linestyle=:dash, color=:black, label="N-S")
    xlims!(0.0, 50.0)
    ylims!(0.0, 0.8)
    xlabel!("a")
    ylabel!("β")
    annotate!([-8.5],[0.75],("b)", 18, "Computer Modern"))
    plot!(left_margin=4mm,legend=:outerright)
    plot(p1, p2, layout=@layout([a{0.42w} b{0.58w}]), size=(1200, 400),bottom_margin=8mm)
    savefig(joinpath(abpath(), "figs/aCbetabifurcation_RickerRicker.svg"))
end

#Tau orbit for a and C comparison (RickerRicker)
let 
    τrange = 1:1:35
    par1 = RickerPar(a=26.5,C=0.5, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RLorbitdata1 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par1, 0.1, LeslieMatrix))
    par2 = RickerPar(a=26.5,C=0.1, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RLorbitdata2 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par2, 0.1, LeslieMatrix))
    par3 = RickerPar(a=26.5, β=0.5, C=0.3, τ=2.0, α=0.1, b=200, K=1.0)
    RLorbitdata3 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par3, 0.1, LeslieMatrix))
    par4 = RickerPar(a=26.5, β=0.1, C=0.3, τ=2.0, α=0.1, b=200, K=1.0)
    RLorbitdata4 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par4, 0.1, LeslieMatrix))
    par5 = RickerPar(a=26.5,C=0.3, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RLorbitdata5 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par5, 0.1, LeslieMatrix))
    
    p1 = scatter(RLorbitdata1[1], RLorbitdata1[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    xlims!(0.0, 15.5)
    title!("C>β")
    annotate!([-5],[0.49],("d)", 18, "Computer Modern"))
    p2 = scatter(RLorbitdata2[1], RLorbitdata2[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    title!("C<β")
    xlims!(0.0, 15.5)
    annotate!([-5],[1.7],("e)", 18, "Computer Modern"))
    p3 = scatter(RLorbitdata3[1], RLorbitdata3[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    title!("C<β")
    xlims!(0.0, 15.5)
    annotate!([-5],[0.67],("f)", 18, "Computer Modern"))
    p4 = scatter(RLorbitdata4[1], RLorbitdata4[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    title!("C>β")
    xlims!(0.0, 15.5)
    annotate!([-5],[0.82],("g)", 18, "Computer Modern"))
    p5= scatter(RLorbitdata5[1], RLorbitdata5[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    title!("C=β")
    xlims!(0.0, 15.5)
    annotate!([-5],[0.75],("c)", 18, "Computer Modern"))
    plot(p1, p3,p5,p2,p4, size=(950, 700), layout=(2, 3), legend=:none,left_margin=5mm)
    savefig(joinpath(abpath(), "figs/RickerRicker_aCbeta_tauorbit.svg"))
end



#Appendix

#Tau create and then kill oscillations
let 
    par = RickerPar(a=13.0, p=0.57205, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RCorbitdata = flattenorbitdata(orbitdiagrams(RickerConstant_model, "τ", par, 50; optτ=2, upperval=8))
    RCorbitdata_wofec = flattenorbitdata(orbitdiagrams(RickerConstant_wofec_model, "τ", par, 50; optτ=2, upperval=8))
    timeseries = model_recursion(10.0, 1000000, RickerPar(a=13.0, p=0.57205, τ=1.0, α=0.1, β=0.3, b=200, K=1.0), RickerConstant_wofec_model; optτ=2)
    dataN = timeseries[end-50:end]
    p2 = scatter(RCorbitdata[1], log10.(RCorbitdata[2] .+1), color=:black, ms=8,label="With fecundity\nbenefit")
    scatter!(RCorbitdata_wofec[1], log10.(RCorbitdata_wofec[2] .+1), color=:blue, ms=5, markerstrokecolor=:blue, label="Without fecundity\nbenefit")
    scatter!([1.0], [0.0], color=:black, ms=8, label="")
    scatter!(repeat([1],51), log10.(dataN .+1), color=:blue, ms=5, markerstrokecolor=:blue, label="")
    xlabel!("τ")
    ylabel!("log10(N+1)")
    xticks!([0, 2, 4, 6, 8])
    xlims!(0.0, 8.5)
    plot!(size=(350, 300))
    savefig(joinpath(abpath(), "figs/RickerConstant_tauorbita.pdf"))
end

#Tau allows equilibrium to exist and then kills stable point
let
    par = RickerPar(a=13.0, p=0.35, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RCorbitdata = flattenorbitdata(orbitdiagrams(RickerConstant_model, "τ", par, 50; upperval=8))
    RCorbitdata_wofec = flattenorbitdata(orbitdiagrams(RickerConstant_wofec_model, "τ", par, 50; optτ=2, upperval=8))
    timeseries = model_recursion(10.0, 1000000, RickerPar(a=13.0, p=0.35, τ=1.0, α=0.1, β=0.3, b=200, K=1.0), RickerConstant_wofec_model; optτ=2)
    dataN = timeseries[end-50:end]
    p2 = scatter(RCorbitdata[1], RCorbitdata[2], color=:black, ms=8, label="With fecundity\nbenefit")
    scatter!(RCorbitdata_wofec[1], log10.(RCorbitdata_wofec[2] .+1), color=:blue, ms=5, markerstrokecolor=:blue, label="Without fecundity\nbenefit")
    scatter!([1.0], [0.0], color=:black, ms=8,label="")
    scatter!(repeat([1],51), log10.(dataN .+1), color=:blue, ms=5, markerstrokecolor=:blue, label="")
    xlabel!("τ")
    ylabel!("N")
    xlims!(0.0, 8.5)
    xticks!([0, 2, 4, 6, 8])
    plot!(size=(350, 300))
    savefig(joinpath(abpath(), "figs/RickerConstant_tauorbitb.pdf"))
end

#Ricker Ricker
#Tau orbit when decreasing C and beta at same time
let 
    τrange = 1:1:35
    par1 = RickerPar(a=26.5,C=0.5, τ=2.0, α=0.1, β=0.5, b=200, K=1.0)
    RLorbitdata1 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par1, 0.1, LeslieMatrix))
    par2 = RickerPar(a=26.5,C=0.3, τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RLorbitdata2 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par2, 0.1, LeslieMatrix))
    par3 = RickerPar(a=26.5,C=0.1, τ=2.0, α=0.1, β=0.1, b=200, K=1.0)
    RLorbitdata3 = flattenorbitdata(LeslieMatrixOrbitDiagram(τrange, 50000, 50, par3, 0.1, LeslieMatrix))
    p1 = scatter(RLorbitdata1[1], RLorbitdata1[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    xlims!(0.0, 35.5)
    # ylims!(0.0, 2.3)
    p2 = scatter(RLorbitdata2[1], RLorbitdata2[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    xlims!(0.0, 35.5)
    #  ylims!(0.0, 2.3)
    p3= scatter(RLorbitdata3[1], RLorbitdata3[2], color=:black, ms=5,label="")
    xlabel!("\$\\tau\$")
    ylabel!("N")
    xlims!(0.0, 35.5)
    #  ylims!(0.0, 2.3)
    plot(p1, p2, p3, size=(450, 600), layout=(3, 1), legend=:none)
    savefig(joinpath(abpath(), "figs/RickerRicker_Cequalbeta_tauorbit.pdf"))
end