include("packages.jl")
include("TradeOffs_CommonCode.jl")

"""
    cleanxppautdat(file_path::String) -> DataFrame

Reads and processes data from a file, returning a cleaned DataFrame.

# Arguments
- `file_path::String`: Path to the data file.

# Returns
- `DataFrame`: Cleaned DataFrame with columns `:a`, `:Lowp`, and `:PointTypeName`.
"""
function cleanxppautdat(file_path)
    datalm = readdlm(file_path)
    data = DataFrame(datalm, [:a, :Low2ndpar, :High2ndpar, :PointType1, :LineNum, :PointType2])
    @select!(data, :a, :Low2ndpar, :PointType1, :PointType2)
    @transform!(data, :PointType1 = Int.(:PointType1), :PointType2 = Int.(:PointType2))
    @transform!(data, :PointType = string.(:PointType1) .* string.(:PointType2))
    @transform!(data, :PointTypeName = ifelse.(:PointType .== "25", "BP", ifelse.(:PointType .== "23", "HP", "Other")))
    @select!(data, :a, :Low2ndpar, :PointTypeName)
    data = sort(data, :Low2ndpar)
    return data
end

let 
    alow=alowerconstraint(RickerPar(p=0.3,τ=2.0, α=0.1, β=0.3, b=200, K=1.0))
    arange=alow:0.1:15.0
    fillbottom = zeros(length(arange))
    data=cleanxppautdat("src/xppaut/RickerConstanttau2.dat")
    bp_data = unique(@subset(data, :PointTypeName .== "BP"), :Lowp)
    hp_data = unique(@subset(data, :PointTypeName .== "HP"), :Lowp)
    phigh=[phigherconstraint(RickerPar(a=aval,τ=2.0, α=0.1, β=0.3, b=200, K=1.0)) for aval in arange]
    plot(bp_data.a, bp_data.Lowp, label="Transcritical",lw=2)
    plot!(hp_data.a, hp_data.Lowp, label="Neimarck-Sacker",lw=2)
    plot!(arange, fillbottom, fillrange = phigh, fillalpha = 0.2, c = 1, label = "Parameter space")
    xlabel!("a")
    ylabel!("p")
    xlims!(9.8, 14.5)
    ylims!(0.0, 1.0)
    title!("τ = 2.0")
end

let 
    alow=alowerconstraint(RickerPar(p=0.3,τ=3.0, α=0.1, β=0.3, b=200, K=1.0))
    arange=alow:0.1:15.0
    fillbottom = zeros(length(arange))
    data=cleanxppautdat("src/xppaut/RickerConstanttau3woPD.dat")
    bp_data = unique(@subset(data, :PointTypeName .== "BP"), :Lowp)
    hp_data = unique(@subset(data, :PointTypeName .== "HP"), :Lowp)
    phigh=[phigherconstraint(RickerPar(a=aval,τ=3.0, α=0.1, β=0.3, b=200, K=1.0)) for aval in arange]
    pddata=perioddoublecurve(4.3:0.1:15.0, 3)
    # return pddata
    plot(bp_data.a, bp_data.Lowp, label="Transcritical",lw=2)
    plot!(hp_data.a, hp_data.Lowp, label="Neimarck-Sacker",lw=2)
    plot!(pddata[:,1], pddata[:,2], label="Period doubling",lw=2)
    plot!(arange, fillbottom, fillrange = phigh, fillalpha = 0.2, c = 1, label = "Parameter space")
    xlabel!("a")
    ylabel!("p")
    xlims!(0.0, 15.0)
    ylims!(0.0, 1.0)
    title!("τ = 3.0")
    savefig(joinpath(abpath(), "figs/RickerConstanttau3wPD.pdf"))
end

let 
    alow=alowerconstraint(RickerPar(p=0.3,τ=4.0, α=0.1, β=0.3, b=200, K=1.0))
    arange=alow:0.1:15.0
    fillbottom = zeros(length(arange))
    data=cleanxppautdat("src/xppaut/RickerConstanttau4.dat")
    bp_data = unique(@subset(data, :PointTypeName .== "BP"), :Lowp)
    hp_data = unique(@subset(data, :PointTypeName .== "HP"), :Lowp)
    phigh=[phigherconstraint(RickerPar(a=aval,τ=4.0, α=0.1, β=0.3, b=200, K=1.0)) for aval in arange]
    plot(bp_data.a, bp_data.Lowp, label="Transcritical",lw=2)
    plot!(hp_data.a, hp_data.Lowp, label="Neimarck-Sacker",lw=2)
    plot!(pddata[:,1], pddata[:,2], label="Period doubling",lw=2)
    plot!(arange, fillbottom, fillrange = phigh, fillalpha = 0.2, c = 1, label = "Parameter space")
    xlabel!("a")
    ylabel!("p")
    xlims!(0.0, 15.0)
    ylims!(0.0, 1.0)
    title!("τ = 4.0")
end

let 
    alow=alowerconstraint(RickerPar(p=0.3,τ=5.0, α=0.1, β=0.3, b=200, K=1.0))
    arange=alow:0.1:22.0
    fillbottom = zeros(length(arange))
    data=cleanxppautdat("src/xppaut/RickerConstanttau5.dat")
    bp_data = unique(@subset(data, :PointTypeName .== "BP"), :Lowp)
    hp_data = unique(@subset(data, :PointTypeName .== "HP"), :Lowp)
    pddata=perioddoublecurve(5.6:0.1:22.0, 5)
    phigh=[phigherconstraint(RickerPar(a=aval,τ=5.0, α=0.1, β=0.3, b=200, K=1.0)) for aval in arange]
    plot(bp_data.a, bp_data.Lowp, label="Transcritical",lw=2)
    plot!(hp_data.a, hp_data.Lowp, label="Neimarck-Sacker",lw=2)
    plot!(pddata[:,1], pddata[:,2], label="Period doubling",lw=2)
    plot!(arange, fillbottom, fillrange = phigh, fillalpha = 0.2, c = 1, label = "Parameter space")
    xlabel!("a")
    ylabel!("p")
    xlims!(0.0, 22.0)
    ylims!(0.0, 1.0)
    title!("τ = 5.0")
end

let 
    datatau2 = cleanxppautdat("src/xppaut/RickerConstanttau2.dat")
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Lowp)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Lowp)
    datatau3 = cleanxppautdat("src/xppaut/RickerConstanttau3woPD.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Lowp)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Lowp)
    datatau4 = cleanxppautdat("src/xppaut/RickerConstanttau4.dat")    
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Lowp)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Lowp)
    datatau5 = cleanxppautdat("src/xppaut/RickerConstanttau5.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Lowp)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Lowp)
    plot(bp_datatau2.a, bp_datatau2.Lowp, lw=2, linestyle=:solid, color=:blue,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Lowp, lw=2, linestyle=:dash, color=:blue,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Lowp, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Lowp, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Lowp, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Lowp, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Lowp, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Lowp, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,22.0)
    ylims!(0.0, 1.0)
    xlabel!("a")
    ylabel!("p")
    savefig(joinpath(abpath(), "figs/apbifurcation_RickerConstant.pdf"))
end


#Tau create and then kill oscillations
let
    par=RickerPar(a=13.0,p=0.57205,τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RCorbitdata = flattenorbitdata(orbitdiagrams(RickerConstant_model, "τ", par, 50;upperval=5))
    p2=scatter(RCorbitdata[1], log.(RCorbitdata[2]),color=:black, label="")
    xlabel!("τ")
    ylabel!("log(N)")
    xlims!(0.0,5.0)
    # savefig(joinpath(abpath(), "figs/tauorbitdiagram_RickerRicker.pdf"))
end


#Tau allows equilibrium to exist and then kills stable point
datatau5 = cleanxppautdat("src/xppaut/RickerConstanttau5.dat")    
@subset(datatau5, :PointTypeName .== "BP")
@subset(datatau5, :a .<10.1)

let
    par=RickerPar(a=10.0138,p=0.464,τ=2.0, α=0.1, β=0.3, b=200, K=1.0)
    RCorbitdata = flattenorbitdata(orbitdiagrams(RickerConstant_model, "τ", par, 50;upperval=5))
    p2=scatter(RCorbitdata[1], RCorbitdata[2],color=:black, label="")
    xlabel!("τ")
    ylabel!("N")
    xlims!(0.0,5.0)
    # savefig(joinpath(abpath(), "figs/tauorbitdiagram_RickerRicker.pdf"))
end


#RickerRicker
#a and C two par bifurcation figure

let 
    datatau1 = cleanxppautdat("src/xppaut/RickerRickertau1_C.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar)
    datatau2 = cleanxppautdat("src/xppaut/RickerRickertau2_C.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/RickerRickertau3_C.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/RickerRickertau4_C.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/RickerRickertau5_C.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=1")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,50.0)
    ylims!(0.0, 10.0)
    xlabel!("a")
    ylabel!("C")
    savefig(joinpath(abpath(), "figs/aCbifurcation_RickerRicker.pdf"))
end

let 
    datatau1 = cleanxppautdat("src/xppaut/RickerRickertau1_C.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar)
    datatau2 = cleanxppautdat("src/xppaut/RickerRickertau2_C.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/RickerRickertau3_C.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/RickerRickertau4_C.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/RickerRickertau5_C.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=1")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,50.0)
    ylims!(0.0, 0.6)
    xlabel!("a")
    ylabel!("C")
    title!("Zoomed in")
    savefig(joinpath(abpath(), "figs/aCbifurcation_RickerRicker_weakcomp.pdf"))
end

let 
    datatau1 = cleanxppautdat("src/xppaut/RickerRickertau1_beta.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar)
    datatau2 = cleanxppautdat("src/xppaut/RickerRickertau2_beta.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/RickerRickertau3_beta.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/RickerRickertau4_beta.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/RickerRickertau5_beta.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=1")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,70.0)
    ylims!(0.0, 10.0)
    xlabel!("a")
    ylabel!("β")
    savefig(joinpath(abpath(), "figs/abetabifurcation_RickerRicker.pdf"))
end

let 
    datatau1 = cleanxppautdat("src/xppaut/RickerRickertau1_beta.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar)
    datatau2 = cleanxppautdat("src/xppaut/RickerRickertau2_beta.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/RickerRickertau3_beta.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/RickerRickertau4_beta.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/RickerRickertau5_beta.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=1")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,70.0)
    ylims!(0.0, 0.3)
    xlabel!("a")
    ylabel!("β")
    title!("Zoomed in")
    savefig(joinpath(abpath(), "figs/abetabifurcation_RickerRicker_weak.pdf"))
end

#BevertonHoltRicker
#a and C two par bifurcation figure

let 
    datatau0 = cleanxppautdat("src/xppaut/BevertonHoltRickertau0_C.dat")
    bp_datatau0 = unique(@subset(datatau0, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau0 = sort(unique(@subset(datatau0, :PointTypeName .== "HP"), :Low2ndpar),:a)
    datatau1 = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_C.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = sort(unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar),:a)
    datatau2 = cleanxppautdat("src/xppaut/BevertonHoltRickertau2_C.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/BevertonHoltRickertau3_C.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/BevertonHoltRickertau4_C.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/BevertonHoltRickertau5_C.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau0.a, bp_datatau0.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=0")
    plot!(hp_datatau0.a, hp_datatau0.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=0")
    plot!(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:brown,label="BP τ=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2, linestyle=:dash, color=:brown,label="HP τ=1")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:orange,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:orange,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,50.0)
    ylims!(0.0, 10.0)
    xlabel!("a")
    ylabel!("C")
    savefig(joinpath(abpath(), "figs/aCbifurcation_BevertonHoltRicker.pdf"))
end

let 
    datatau0 = cleanxppautdat("src/xppaut/BevertonHoltRickertau0_C.dat")
    bp_datatau0 = unique(@subset(datatau0, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau0 = sort(unique(@subset(datatau0, :PointTypeName .== "HP"), :Low2ndpar),:a)
    datatau1 = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_C.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = sort(unique(@subset(datatau1, :PointTypeName .== "HP"), :Low2ndpar),:a)
    datatau2 = cleanxppautdat("src/xppaut/BevertonHoltRickertau2_C.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/BevertonHoltRickertau3_C.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/BevertonHoltRickertau4_C.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/BevertonHoltRickertau5_C.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau0.a, bp_datatau0.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=0")
    plot!(hp_datatau0.a, hp_datatau0.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=0")
    plot!(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:brown,label="BP τ=1")
    plot!(hp_datatau1.a, hp_datatau1.Low2ndpar, lw=2, linestyle=:dash, color=:brown,label="HP τ=1")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:orange,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:orange,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,200.0)
    ylims!(0.0, 0.15)
    xlabel!("a")
    ylabel!("C")
    title!("Zoomed in")
    savefig(joinpath(abpath(), "figs/aCbifurcation_BevertonHoltRicker_weakcomp.pdf"))
end

let 
    datatau1 = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_beta.dat")
    bp_datatau1 = unique(@subset(datatau1, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1 = sort(unique(@subset(datatau1, :PointTypeName .== "HP" .&& :a .<= 50.0), :a), :a)
    CSV.write("hp_datatau1.csv", hp_datatau1)
    # return hp_datatau1
end


let 
    datatau0 = cleanxppautdat("src/xppaut/BevertonHoltRickertau0_beta.dat")
    bp_datatau0 = unique(@subset(datatau0, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau0 = sort(unique(@subset(datatau0, :PointTypeName .== "HP"), :a),:a)
    datatau1_a = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_beta_adata.dat")
    datatau1_b = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_beta_bdata.dat")
    bp_datatau1 = unique(@subset(datatau1_a, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1a = unique(@subset(datatau1_a, :PointTypeName .== "HP"), :Low2ndpar)
    hp_datatau1b = sort(unique(@subset(datatau1_b, :PointTypeName .== "HP"), :a),:a)
    hp_datatau1=vcat(hp_datatau1a, hp_datatau1b)
    datatau2 = cleanxppautdat("src/xppaut/BevertonHoltRickertau2_beta.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/BevertonHoltRickertau3_beta.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/BevertonHoltRickertau4_beta.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/BevertonHoltRickertau5_beta.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau0.a, bp_datatau0.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=0")
    plot!(hp_datatau0.a, hp_datatau0.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=0")
    plot!(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:brown,label="BP τ=1")
    plot!(hp_datatau1a.a, hp_datatau1a.Low2ndpar, lw=2, linestyle=:dash, color=:brown,label="HP τ=1")
    plot!(hp_datatau1b.a, hp_datatau1b.Low2ndpar, lw=2, linestyle=:dash, color=:brown,label="")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:orange,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:orange,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0,100.0)
    ylims!(0.0, 10.0)
    xlabel!("a")
    ylabel!("β")
    savefig(joinpath(abpath(), "figs/abetabifurcation_BevertonHoltRicker.pdf"))
end

let 
    datatau0 = cleanxppautdat("src/xppaut/BevertonHoltRickertau0_beta.dat")
    bp_datatau0 = unique(@subset(datatau0, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau0 = sort(unique(@subset(datatau0, :PointTypeName .== "HP"), :a),:a)
    datatau1_a = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_beta_adata.dat")
    datatau1_b = cleanxppautdat("src/xppaut/BevertonHoltRickertau1_beta_bdata.dat")
    bp_datatau1 = unique(@subset(datatau1_a, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau1a = unique(@subset(datatau1_a, :PointTypeName .== "HP"), :Low2ndpar)
    hp_datatau1b = sort(unique(@subset(datatau1_b, :PointTypeName .== "HP"), :a),:a)
    hp_datatau1=vcat(hp_datatau1a, hp_datatau1b)
    datatau2 = cleanxppautdat("src/xppaut/BevertonHoltRickertau2_beta.dat")    
    bp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau2 = unique(@subset(datatau2, :PointTypeName .== "HP"), :Low2ndpar)
    datatau3 = cleanxppautdat("src/xppaut/BevertonHoltRickertau3_beta.dat")    
    bp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau3 = unique(@subset(datatau3, :PointTypeName .== "HP"), :Low2ndpar)
    datatau4 = cleanxppautdat("src/xppaut/BevertonHoltRickertau4_beta.dat")
    bp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau4 = unique(@subset(datatau4, :PointTypeName .== "HP"), :Low2ndpar)
    datatau5 = cleanxppautdat("src/xppaut/BevertonHoltRickertau5_beta.dat")
    bp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "BP"), :Low2ndpar)
    hp_datatau5 = unique(@subset(datatau5, :PointTypeName .== "HP"), :Low2ndpar)
    plot(bp_datatau0.a, bp_datatau0.Low2ndpar, lw=2, linestyle=:solid, color=:blue,label="BP τ=0")
    plot!(hp_datatau0.a, hp_datatau0.Low2ndpar, lw=2, linestyle=:dash, color=:blue,label="HP τ=0")
    plot!(bp_datatau1.a, bp_datatau1.Low2ndpar, lw=2, linestyle=:solid, color=:brown,label="BP τ=1")
    plot!(hp_datatau1a.a, hp_datatau1a.Low2ndpar, lw=2, linestyle=:dash, color=:brown,label="HP τ=1")
    plot!(hp_datatau1b.a, hp_datatau1b.Low2ndpar, lw=2, linestyle=:dash, color=:brown,label="")
    plot!(bp_datatau2.a, bp_datatau2.Low2ndpar, lw=2, linestyle=:solid, color=:orange,label="BP τ=2")
    plot!(hp_datatau2.a, hp_datatau2.Low2ndpar, lw=2, linestyle=:dash, color=:orange,label="HP τ=2")
    plot!(bp_datatau3.a, bp_datatau3.Low2ndpar, lw=2, linestyle=:solid, color=:purple, label="BP τ=3")
    plot!(hp_datatau3.a, hp_datatau3.Low2ndpar, lw=2, linestyle=:dash, color=:purple,label="HP τ=3")
    plot!(bp_datatau4.a, bp_datatau4.Low2ndpar, lw=2, linestyle=:solid, color=:red, label="BP τ=4")
    plot!(hp_datatau4.a, hp_datatau4.Low2ndpar, lw=2, linestyle=:dash, color=:red,label="HP τ=4")
    plot!(bp_datatau5.a, bp_datatau5.Low2ndpar, lw=2, linestyle=:solid,color=:green, label="BP τ=5")
    plot!(hp_datatau5.a, hp_datatau5.Low2ndpar, lw=2, linestyle=:dash, color=:green, label="HP τ=5")
    xlims!(0.0,400.0)
    ylims!(0.0, 0.3)
    xlabel!("a")
    ylabel!("β")
    title!("Zoomed in")
    savefig(joinpath(abpath(), "figs/abetabifurcation_BevertonHoltRicker_weak.pdf"))
end

